name: Helm Deploy to Minikube

on:
  push:
    branches: [ main ]
    paths:
      - '**.yaml'
      - 'charts/**'
      - 'app/**'
      - 'Dockerfile'

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.0
        options: --privileged
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env)
          docker build -t myapp:latest .

      - name: Helm Install for Test
        run: |
          helm upgrade --install myapp-test ./charts/myapp -f env/test-values.yaml

      - name: Helm Install for Stage
        run: |
          helm upgrade --install myapp-stage ./charts/myapp -f env/stage-values.yaml

      - name: Helm Install for Prod
        run: |
          helm upgrade --install myapp-prod ./charts/myapp -f env/prod-values.yaml

      - name: Validate Services
        run: |
          kubectl get all
