name: Multi-Job CI/CD with Helm and Minikube

on:
  push:
    branches: [ main ]
    paths:
      - '**.yaml'
      - 'charts/**'
      - 'app/**'
      - 'Dockerfile'

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      docker-env: ${{ steps.set-env.outputs.DOCKER_ENV }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set Docker Env from Minikube
        id: set-env
        run: echo "DOCKER_ENV=$(minikube docker-env --shell bash)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Re-run Minikube and Docker Context
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          eval $(minikube docker-env)
          docker build -t myapp:latest .

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to Test Environment
        run: |
          eval $(minikube docker-env)
          helm upgrade --install myapp-test ./charts/myapp -f env/test-values.yaml

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to Stage Environment
        run: |
          eval $(minikube docker-env)
          helm upgrade --install myapp-stage ./charts/myapp -f env/stage-values.yaml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to Prod Environment
        run: |
          eval $(minikube docker-env)
          helm upgrade --install myapp-prod ./charts/myapp -f env/prod-values.yaml
